[package]
name = "digital-garden"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
handlebars = "5.1.2"
pulldown-cmark = "0.11.0"
serde_json = "1.0.118"
walkdir = "2.5.0"
