name: deploy
on:
  push:
    branches: ["main"]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: rust setup
        uses: dtolnay/rust-toolchain@stable
      - name: setup cache
        uses: Swatinem/rust-cache@v2
      - name: install dependencies
        run: cargo install cliche
      - name: build site
        run: cliche ./content
      - name: setup pages
        uses: actions/configure-pages@v5
      - name: upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './_site'
      - name: deploy to gh pages
        id: deployment
        uses: actions/deploy-pages@v4
